name: Build Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            software-properties-common

          curl -fsSL https://download.docker.com/linux/ubuntu/gpg  | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu  \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Build Docker image
        run: |
          docker build -t cpp-builder .

      - name: Run and build inside container
        run: |
          mkdir -p logs
          docker run --rm \
            -v $(pwd):/app \
            -v $(pwd)/logs:/logs \
            cpp-builder \
            sh -c "cd /app && cmake . && make > /logs/build.log 2>&1"

      - name: Upload compilation log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: logs/build.log
